import type { Metadata } from "next";
import { Lobster ,Dancing_Script,Onest,Headland_One, Libre_Baskerville,Suez_One,Space_Mono,Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
// import {Lobster ,Dancing_Script,Onest,Headland_One, Libre_Baskerville} from "next/font/google";


const suezOne = Suez_One({
  variable: "--font-suez-one",
  subsets: ["latin"],
  weight: "400",
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "700",
});

const Lobsterfont  =  Lobster({
  variable: "--font-lobster",
  subsets: ['latin'],
  weight: "400"
})


const onestfont  =  Onest({
  variable:"--font-onest",
  subsets:['latin']
})


const Librefont  =  Libre_Baskerville({
  variable:"--libre-font",
  subsets:['latin'],
  weight:"400"
})

const Headlandfont  = Headland_One({
  variable:"--heading-font",
  subsets:['latin'],
  weight:"400"
})


const dancingfont = Dancing_Script({
  variable:"--font-dancing",
  subsets:['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.variable} ${suezOne.variable}  ${montserrat.variable} ${onestfont.variable} ${dancingfont.variable} ${Lobsterfont.variable} ${Librefont.variable} ${Headlandfont.variable} antialiased bg-background`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
